package:
  name: hydra       # lower case name of package, may contain '-' but no spaces
  version: "1.0.2"    # version of package. Should use the PEP-386 verlib
                      # conventions. Note that YAML will interpret
                      # versions like 1.0 as floats, meaning that 1.0 will
                      # be the same as 1. To avoid this, always put the
                      # version in quotes, so that it will be interpreted
                      # as a string.

                      # The version cannot contain a dash '-' character.

source:
   git_url: https://montilab@github.com/montilab/Hydra.git
   git_tag: 'v1.0.2'

build:
  number: 2       # (defaults to 0)
  string: monti_2       # (defaults to default conda build string plus the build
                  # number)
                  # The build string cannot contain a dash '-' character

  detect_binary_files_with_prefix: true # (defaults to false)

requirements:
   build:
    - python 2.7*
    - pysam
    - matplotlib
    - numpy
    - biopython
    - mock
    - nose
    
   run:
    - samtools 0.1.19
    - bowtie2 2.2.2
    - cufflinks 2.2.0
    - cutadapt 1.8.1
    - fastqc 0.11.2
    - htseq 0.6.1p1
    - pysam 0.7.7
    - r-base 3.3.1
    - subread 1.4.6
    - tophat 2.0.13
    - python 2.7*
    - matplotlib
    - mock
    - nose
    - numpy
    - biopython
    - star 2.4.1d

test:
   requires:
     - python 2.7*

   commands:
    - python2.7 -c "import hydra_pkg"
    - python2.7 -c "import hydra_pkg.pipeline"
    - hydra-rnaseq -h

about:
  home: https://github.com/yannpaul/CBMgithub
  license: BSD
